{% set version = "0.10.2" %}

package:
  name: nanopolish
  version: "{{ version }}"

about:
  home: https://github.com/jts/nanopolish
  license: MIT
  summary: "Software package for signal-level analysis of Oxford Nanopore sequencing data."

build:
  number: 0

source:
  git_url: https://github.com/jts/nanopolish.git
  git_rev: v{{ version }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - make
  host:
    - eigen
    - libhdf5-dev
    - libbz2-dev
    - libhts-dev
    - liblzma-dev
    - libz-dev
  run:
    - libbz2
    - libhdf5
    - libhts
    - liblzma
    - libz
