{% set version = "1.2.0" %}

package:
  name: freebayes
  version: "{{ version }}"

about:
  home: https://github.com/ekg/freebayes
  license: MIT
  summary: Bayesian haplotype-based genetic polymorphism discovery and genotyping.

build:
  number: 1

source:
  git_url: https://github.com/ekg/freebayes.git
  git_tag: v{{ version }}
  patches:
    - Makefile.patch
    - src_Makefile.patch
    - SeqLib_bwa_Makefile.patch
    - SeqLib_fermi-lite_Makefile.patch
    - vcflib_Makefile.patch
    - vcflib_smithwaterman_Makefile.patch
    - vcflib_tabixpp_Makefile.patch
    - vcflib_tabixpp_htslib_Makefile.patch

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - automake
    - make
    - perl
  host:
    - libbz2-dev
    - libcurl-dev
    - liblzma-dev
    - libssl-dev
    - libz-dev
  run:
    - libbz2
    - libcurl
    - liblzma
    - libssl
    - libz

test:
  commands:
    - freebayes --help
