{% set version = "1.9" %}
{% set htslib_version = "1.9" %}
{% set sha256 = "6f36d0e6f16ec4acf88649fb1565d443acf0ba40f25a9afd87f14d14d13070c8" %}

package:
  name: bcftools
  version: "{{ version }}"

about:
  home: https://github.com/samtools/bcftools
  license: MIT
  summary: VCF commands and BCF calling.

build:
  number: 2

source:
  url: https://github.com/samtools/bcftools/releases/download/{{ version }}/bcftools-{{ version }}.tar.bz2
  fn: bcftools-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - make
  host:
    - libhts-dev =={{ htslib_version }}
    - libz-dev
  run:
    - libhts =={{ htslib_version }}
    - libz

test:
  commands:
    - bcftools --help
