{% set version = "8.41" %}
{% set sha256 = "244838e1f1d14f7e2fa7681b857b3a8566b74215f28133f14a8f5e59241b682c" %}

package:
  name: pcre-pkg
  version: "{{ version }}"

about:
  home: http://www.pcre.org/
  license: BSD
  summary: "Perl Compatible Regular Expressions."

build:
  number: 4

source:
  url: https://ftp.pcre.org/pub/pcre/pcre-{{ version }}.tar.gz
  fn: pcre-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - make
  host:
    - libbz2-dev
    - liblzma-dev
    - libz-dev
  run:
    - libbz2
    - liblzma
    - libz

outputs:
  - name: pcre
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - make
      host:
        - libbz2-dev
        - liblzma-dev
        - libz-dev
      run:
        - {{ pin_subpackage("libpcre", exact=True) }}
        - libbz2
        - liblzma
        - libz
    files:
      - bin/pcregrep
      - bin/pcretest
    test:
      commands:
        - pcregrep --help

  - name: libpcre
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - make
      host:
        - libbz2-dev
        - liblzma-dev
        - libz-dev
      run:
        - libbz2
        - liblzma
        - libz
    files:
      - lib/libpcre*.*
    test:
      commands:
        - test -f ${PREFIX}/lib/libpcre.a
        - test -h ${PREFIX}/lib/libpcre.so

  - name: libpcre-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libpcre", exact=True) }}
    files:
      - bin/pcre-config
      - include/pcre*.h
      - lib/pkgconfig/libpcre*.pc
    test:
      commands:
        - test -f ${PREFIX}/include/pcre.h
