{% set version = "0.11.1" %}
{% set min_hts_version = "1.3.1" %}

package:
  name: bambi
  version: "{{ version }}"

about:
  home: https://github.com/wtsi-npg/bambi
  license: AGPL
  summary: "A set of programs to manipulate SAM/BAM/CRAM files, using HTSLIB."

build:
  number: 4

source:
  git_url: https://github.com/wtsi-npg/bambi.git
  git_rev: 0.11.1
  patches:
    - ax_with_htslib.patch

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - automake
    - make
    - perl
    - pkg-config
  host:
    - libgd-dev
    - libhts-dev >={{ min_hts_version }}
    - libxml2-dev
    - libz-dev
  run:
    - libgd
    - libhts >={{ min_hts_version }}
    - libxml2
    - libz

test:
  commands:
    - bambi --version
