{% set version = "0.7.17" %}

package:
  name: bwa
  version: "{{ version }}"

about:
  home: https://github.com/lh3/bwa
  license: GPL3
  summary: Burrows-Wheeler Aligner for short-read alignment.

build:
  number: 2

source:
  - git_url: https://github.com/lh3/bwa.git
    git_rev: v{{ version }}
    patches:
      - Makefile.patch

requirements:
  build:
    - {{ compiler("c") }}
    - make
  host:
    - libz-dev
  run:
    - libz

test:
  commands:
    - test -x ${PREFIX}/bin/bwa
