{% set version = "2.18" %}
{% set sha256 = "7a55101d58ecaec545db51079ad82b214632dc697ee67290b6dc34cc70dbeeb4" %}

package:
  name: minimap2
  version: "{{ version }}"

about:
  home: https://lh3.github.io/minimap2
  license: MIT
  summary: "A versatile pairwise aligner for genomic and spliced nucleotide sequences."

build:
  number: 0

source:
  url: https://github.com/lh3/minimap2/releases/download/v{{ version }}/minimap2-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - make
  host:
    - libz-dev
  run:
    - libz

test:
  commands:
    - minimap2 --version
    - minimap2 2>&1 | grep 'Usage'
    - sdust  2>&1 | grep 'Usage'
#    - paftools.js version | grep {{ version }}

about:
  home: https://github.com/lh3/minimap2
  license: MIT
  license_file: LICENSE.txt
  summary: 'A versatile pairwise aligner for genomic and spliced nucleotide sequences.'

