{% set version = "0.2.0" %}
{% set sha256 = "8b22b6a6340bf8801453886330b1f8ff7d455312124388e6dbaa902f4750baf2" %}

package:
  name: goleft
  version: "{{ version }}"

about:
  home: https://github.com/brentp/goleft
  license: MIT
  summary: "goleft is a collection of bioinformatics tools distributed under MIT license in a single static binary."

build:
  number: 1
  binary_relocation: false

source:
  url: https://github.com/brentp/goleft/releases/download/v{{ version }}/goleft_linux64
  sha256: {{ sha256 }}

requirements:
  run:
    - samtools-bin

test:
  commands:
    - goleft depth -h
    - goleft indexcov -h
