{% set version = "6.1.2" %}
{% set sha256 = "87b565e89a9a684fe4ebeeddb8399dce2599f9c9049854ca8c0dfbdea0e21912" %}

package:
  name: gmplib
  version: "{{ version }}"

about:
  home: https://gmplib.org/
  license: 
  summary: "The GNU Multiple Precision Arithmetic Library."

build:
  number: 2

source:
  url: https://gmplib.org/download/gmp/gmp-{{ version }}.tar.xz
  fn: gmplib-{{ version }}.tar.xz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - m4
    - make
  host:
    - libz-dev
  run:
    - libz

outputs:
  - name: libgmp
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - m4
        - make
      host:
        - libz-dev
      run:
        - libz
    files:
      - lib/libgmp.a
      - lib/libgmp.so*
    test:
      commands:
        - test -f ${PREFIX}/lib/libgmp.a
        - test -h ${PREFIX}/lib/libgmp.so

  - name: libgmp-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libgmp", exact=True) }}
    files:
      - include
      - share
    test:
      commands:
        - test -f ${PREFIX}/include/gmp.h
