{% set version = "1.0.6" %}
{% set sha256 = "d70a9ccd8bdf47e302d96c69fecd54925f45d9c7b966bb4ef5f56b770960afa7" %}

package:
  name: bzip2-pkg
  version: "{{ version }}"

about:
  home: http://bzip.org/index.html
  license: BSD
  summary: Data compressor.

build:
  number: 4

source:
  url: http://http.debian.net/debian/pool/main/b/bzip2/bzip2_{{ version }}.orig.tar.bz2
  fn: bzip2-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - Makefile.patch
    - Makefile-libbz2_so.patch

requirements:
  build:
    - {{ compiler("c") }}
    - make
  
outputs:
  - name: bzip2
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - make
      run:
        - {{ pin_subpackage('libbz2', exact=True) }}
    files:
      - bin/bunzip2
      - bin/bzcat
      - bin/bzcmp
      - bin/bzdiff
      - bin/bzegrep
      - bin/bzfgrep
      - bin/bzgrep
      - bin/bzip2
      - bin/bziprecover
      - bin/bzless
      - bin/bzmore
      - man/man1
    test:
      commands:
        - bzip2 --help
        - bunzip2 --help

  - name: libbz2
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
    files:
      - lib/libbz2.*
    test:
      commands:
        - test -f ${PREFIX}/lib/libbz2.a
        - test -h ${PREFIX}/lib/libbz2.so.1.0

  - name: libbz2-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage('libbz2', exact=True) }}
    files:
      - include
    test:
      commands:
        - test -f ${PREFIX}/include/bzlib.h
