{% set version = "3.3.4" %}
{% set sha256 = "dd254beb0bafc695d0f62ae1a222ff85b52dbaa3a16f76e781dce22d0d20a4a6" %}

package:
  name: eigen
  version: "{{ version }}"

about:
  home: http://eigen.tuxfamily.org
  license: MLP2
  summary: "A C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms."

build:
  number: 1

source:
  url: https://bitbucket.org/eigen/eigen/get/{{ version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - make

