{% set version = "2.2.7" %}

package:
  name: bowtie2
  version: "{{ version }}"

about:
  home: http://bowtie-bio.sourceforge.net/bowtie2/index.shtml
  license: GPL3
  summary: "A fast and sensitive gapped read aligner."

build:
  number: 2

source:
  git_url: https://github.com/BenLangmead/bowtie2.git
  git_rev: ee49a01c536b8b4915a88c469f2f1ccc78bdf70a

requirements:
  build:
    - {{ compiler("cxx") }}
    - make

test:
  commands:
    - bowtie2 -h
