{% set version = "2.1.0" %}
{% set sha256 = "89a276eed1fc07414b1601947bc9466bdeb50e8f148ad42074186fe39a1ee781" %}

package:
  name: hisat2
  version: "{{ version }}"

about:
  home: http://ccb.jhu.edu/software/hisat2/index.shtml
  license: GPL3
  summary: "Graph-based alignment of next generation sequencing reads to a population of genomes."

build:
  number: 1

source:
  url: ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/downloads/hisat2-{{ version }}-source.zip
  fn: hisat2-{{ version }}-source.zip
  sha256: {{ sha256 }}
  patches:
    - Makefile.patch

requirements:
  build:
    - {{ compiler("cxx") }}
    - make
  host:
    - libz-dev
  run:
    - libz

test:
  commands:
    - hisat2 -h
