{% set version = "v2.0pre1_23_gf4f5000" %}
{% set bwa_mem2_rev = "f4f5000c750d4bcaf5079ebf9664b194f2c9d7cf" %}

package:
  name: bwa-mem2
  version: "{{ version }}"

about:
  home: https://github.com/bwa-mem2/bwa-mem2
  license: GPL3
  summary: Burrows-Wheeler Aligner for short-read alignment.

build:
  number: 2

source:
  - git_url: https://github.com/bwa-mem2/bwa-mem2.git
    git_rev: "{{bwa_mem2_rev }}"

    patches:
      - version_flags.patch

requirements:
  build:
    - {{ compiler("cxx") }}
    - make
  host:
    - libz-dev
  run:
    - libz

test:
  commands:
    - test -x ${PREFIX}/bin/bwa-mem2
