{% set version = "1.2.2" %}

package:
  name: bowtie
  version: "{{ version }}"

about:
  home: http://bowtie-bio.sourceforge.net/index.shtml
  license: Perl Artistic Licence
  summary: An ultrafast memory-efficient short read aligner.

build:
  number: 2

source:
  git_url: https://github.com/BenLangmead/bowtie
  git_rev: v{{ version}}_p1

requirements:
  build:
    - {{ compiler("cxx") }}
    - make
  host:
    - tbb-devel
    - libz-dev
  run:
    - tbb
    - libz

test:
  commands:
    - bowtie -h
