{% set version = "1.10.1" %}
{% set short_version = "1.10" %}
{% set sha256 = "9c5ce1e33d2463fb1a42dd04daacbc22104e57676e2204e3d66b1ef54b88ebf2" %}

package:
  name: hdf5-pkg
  version: "{{ version }}"

about:
  home: https://support.hdfgroup.org/HDF5/
  license: BSD
  summary: A data model, library, and file format for storing and managing data.

build:
  number: 4
  string: threadsafe_{{ PKG_BUILDNUM }}

source:
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-{{ short_version }}/hdf5-{{ version }}/src/hdf5-{{ version }}.tar.bz2
  fn: hdf5-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - make
  host:
    - libz-dev
  run:
    - libz

outputs:
  - name: hdf5-all
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libhdf5", exact=True) }}
        - {{ pin_subpackage("libhdf5-dev", exact=True) }}
        - {{ pin_subpackage("hdf5", exact=True) }}

  - name: hdf5
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("cxx") }}
        - make
      host:
        - libz-dev
      run:
        - {{ pin_subpackage("libhdf5", exact=True) }}
        - libz
    files:
      - bin/gif2h5
      - bin/h52gif
      - bin/h5cc
      - bin/h5copy
      - bin/h5debug
      - bin/h5diff
      - bin/h5dump
      - bin/h5import
      - bin/h5jam
      - bin/h5ls
      - bin/h5mkgrp
      - bin/h5perf_serial
      - bin/h5redeploy
      - bin/h5repack
      - bin/h5repart
      - bin/h5stat
      - bin/h5unjam
    test:
      commands:
        - h5dump -h

  - name: libhdf5
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("cxx") }}
        - make
      host:
        - libz-dev
      run:
        - libz
    files:
      - lib/libhdf5.so*
    test:
      commands:
        - test -h ${PREFIX}/lib/libhdf5.so

  - name: libhdf5-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libhdf5", exact=True) }}
    files:
      - lib/libhdf5.a
      - include/H5*
      - include/hdf5*
      - share/hdf5_examples
    test:
      commands:
        - test -f ${PREFIX}/lib/libhdf5.a
        - test -f ${PREFIX}/include/hdf5.h
