{% set version = "4.1.3.0" %}
{% set sha256 = "56fd4f03b15a8a01eaa4629f62e3ab15e4d4b957c787efd2d5629b2658c3df0a" %}

package:
  name: gatk
  version: "{{ version }}"

about:
  home: https://www.broadinstitute.org/gatk/
  license: BSD-3-Clause
  summary: "Genome Analysis Toolkit (GATK4)"

build:
  number: 0
  
source:
  url: https://github.com/broadinstitute/gatk/releases/download/{{ version }}/gatk-{{ version }}.zip
  sha256: {{ sha256 }}

requirements:
  run:
    - openjdk >=8,<9
    - python

