{% set version = "5.2.3" %}
{% set sha256 = "fd9ca16de1052aac899ad3495ad20dfa906c27b4a5070102a2ec35ca3a4740c1" %}

package:
  name: xz-pkg
  version: "{{ version }}"

about:
  home: https://tukaani.org/xz/
  license: Various
  summary: XZ Utils is free general-purpose data compression software.

build:
  number: 3

source:
  url: https://tukaani.org/xz/xz-{{ version }}.tar.bz2
  fn: xz-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - make

outputs:
  - name: xz
    version: {{ version }}
    requirements:
      build:
         - {{ compiler("c") }}
         - make
      run:
        - {{ pin_subpackage('liblzma', exact=True) }}
    files:
      - bin/lzless
      - bin/xzless
      - bin/lzmore
      - bin/xzmore
      - bin/xzegrep
      - bin/lzfgrep
      - bin/xzgrep
      - bin/xzfgrep
      - bin/lzgrep
      - bin/lzegrep
      - bin/xzdiff
      - bin/lzdiff
      - bin/lzcmp
      - bin/xzcmp
      - bin/lzmainfo
      - bin/xzdec
      - bin/lzmadec
      - bin/lzcat
      - bin/lzma
      - bin/xzcat
      - bin/xz
      - bin/unlzma
      - bin/unxz
      - share/man/man1
    test:
      commands:
        - xz --help

  - name: liblzma
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - make
    files:
      - lib/liblzma.*
      - share/locale
    test:
      commands:
        - test -f ${PREFIX}/lib/liblzma.a
        - test -h ${PREFIX}/lib/liblzma.so

  - name: liblzma-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage('liblzma', exact=True) }}
    files:
      - include
      - share/doc
      - lib/pkgconfig/liblzma.pc
    test:
      commands:
        - test -f ${PREFIX}/include/lzma.h
