{% set version = "1.9+128_g7eb338f" %}
{% set htslib_version = "1.9+297_g66c41e2" %}

package:
  name: samtools-pkg
  version: "{{ version }}"

about:
  home: https://github.com/samtools/samtools
  license: MIT
  summary: C library for high-throughput sequencing data formats.

build:
  number: 1

source:
  git_url: https://github.com/samtools/samtools.git
  git_rev: 2d4907cf9a34ccf7cde60143158b39e1cb40ac0c

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - automake
    - make
    - perl
  host:
    - libhts-dev =={{ htslib_version }}
    - libz-dev
  run:
    - libhts =={{ htslib_version }}
    - libz

outputs:
  - name: samtools
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
        - automake
        - make
        - perl
      host:
        - libhts-dev =={{ htslib_version }}
        - libz-dev
      run:
        - libhts =={{ htslib_version }}
        - libz
    files:
      - bin/ace2sam
      - bin/maq2sam-*
      - bin/md5*
      - bin/plot-bamstats
      - bin/samtools
      - bin/wgsim
      - bin/*.pl
      - bin/*.py
    test:
      commands:
        - echo '@HD VN:1.0 SO:coordinate' | samtools view

  - name: samtools-dev
    version: {{ version }}
    requirements:
      run:
        - libhts =={{ htslib_version }}
        - libz
    files:
      - include/samtools/*.h
      - lib/libbam.a
    test:
      commands:
        - test -f ${PREFIX}/include/samtools/sam.h
        - test -f ${PREFIX}/lib/libbam.a
