{% set version = "2.2.5" %}
{% set sha256 = "a66111c9b4a04e818e9e2a37d7ae8d4aae0939a100a36b0ffb52c706a09074b5" %}

package:
  name: libgd-pkg
  version: "{{ version }}"

about:
  home: https://libgd.github.io/
  license: libgd
  summary: "GD is an open source code library for the dynamic creation of images by programmers."

source:
  url: https://github.com/libgd/libgd/releases/download/gd-{{ version }}/libgd-{{ version }}.tar.gz
  fn: libgd-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - libtool
    - make
    - pkg-config
  host:
    - libpng-dev
    - libz-dev
  run:
    - libpng
    - libz

outputs:
  - name: libgd-bin
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - libtool
        - make
        - pkg-config
      host:
        - libpng-dev
        - libz-dev
      run:
        - {{ pin_subpackage("libgd", exact=True) }}
        - libpng
        - libz
    files:
      - bin/*gd*
      - bin/*png*
    test:
      commands:
        - test -x ${PREFIX}/bin/gdtopng

  - name: libgd
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - libtool
        - make
        - pkg-config
      host:
        - libpng-dev
        - libz-dev
      run:
        - libpng
        - libz
    files:
      - lib/libgd.*
    test:
      commands:
        - test -f ${PREFIX}/lib/libgd.a
        - test -h ${PREFIX}/lib/libgd.so

  - name: libgd-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libgd", exact=True) }}
    files:
      - include
      - lib/pkgconfig/gdlib.pc
    test:
      commands:
        - test -f ${PREFIX}/include/gd.h
